application: libertarian-islands
version: 1
runtime: go
api_version: go1


inbound_services:
- mail

skip_files:
- ^(.*/)?\..*$

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico


- url: /images
  static_dir: static/images

- url: /.*
  # magic string:
  script: _go_app